[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  VITE_CJS_TRACE = "1"
  VITE_CJS_IGNORE_WARNING = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"
